# SITE CONFIGURATION
baseurl: "" # Set it to "" if use for personal site. The subpath of your site, e.g. /blog/
url: "http://blog.nuttopan.cn" # the base hostname & protocol for your site
imageurl: "https://source.unsplash.com/category/nature/2600x500/daily" #"https://unsplash.it/2600/500?random"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Nutto的穿梭机
  #avatar: avatar.png
  hometitle: Home #display on navigation menu.
  yoursitetitle: Nutto的穿梭机
  gravatar: # Email MD5 hash
  description: "nutto的博客" # used by search engines
  visiblewords: 75
  # Header and footer text
  header_text: >
     老牛亦解韶光贵,不待扬鞭自奋蹄.

  header_text_feature_image: img/sample_feature_img.png
  place_holder_image: img/sample_feature_img.png
  footer_text: >
   <a href="">Nutto的穿梭机</a> 

  # Icons
  rss: true
  email_address: "nutto.pan@gmail.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "nutto"
  weibo: 
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest: 
  reddit:
  soundcloud:
  stack_exchange: "http://stackoverflow.com/users/4744833/nutto" # Full URL
  steam:
  tumblr:
  twitter: "nutto.pan"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-76816542-1"# Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "blognuttopancn"
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  #str_next: "Next"
  #str_prev: "Prev"
  str_continue_reading: "Continue Reading..."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
enforce_ssl: ""
paginate: 5
paginate_path: "blog/page:num"
permalink: blog/:title/ 

# Posted in ... with ...
sechby: 
  category:   #in
  tag:   #with

# BUILD SETTINGS
markdown: redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-paginate

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Nutto
      category: other
      # feature-img: "img/sample_feature_img.png"